// GENERATED by tool/gen_api.dart from docs/contracts/openapi.yaml. Do not edit.
//
// Regenerate with: dart run tool/gen_api.dart
// CI fails when this file and the contract disagree (dart run tool/gen_api.dart --check).

// ignore_for_file: lines_longer_than_80_chars, unused_element

/// Thrown when the server sends a body this build cannot read: a required field
/// is missing or has the wrong shape. It names the field, because "unexpected
/// null" three screens later is how a contract break turns into a bug report
/// about something else.
class ApiShapeError implements Exception {
  ApiShapeError(this.path, this.detail);

  final String path;
  final String detail;

  @override
  String toString() =>
      'the server sent something this app cannot read at "$path": $detail';
}

Map<String, Object?> _obj(Object? v, String path) {
  if (v is Map) return v.cast<String, Object?>();
  throw ApiShapeError(path, 'expected an object, got ${v.runtimeType}');
}

T _req<T>(
  Map<String, Object?> m,
  String key,
  String path,
  T Function(Object?, String) read,
) {
  if (!m.containsKey(key) || m[key] == null) {
    throw ApiShapeError('$path.$key', 'required field is missing');
  }
  return read(m[key], '$path.$key');
}

T? _opt<T>(
  Map<String, Object?> m,
  String key,
  String path,
  T Function(Object?, String) read,
) {
  final v = m[key];
  return v == null ? null : read(v, '$path.$key');
}

String _str(Object? v, String path) {
  if (v is String) return v;
  throw ApiShapeError(path, 'expected a string, got ${v.runtimeType}');
}

bool _bool(Object? v, String path) {
  if (v is bool) return v;
  throw ApiShapeError(path, 'expected a boolean, got ${v.runtimeType}');
}

int _int(Object? v, String path) {
  if (v is int) return v;
  if (v is num && v == v.roundToDouble()) return v.toInt();
  throw ApiShapeError(path, 'expected an integer, got ${v.runtimeType}');
}

double _num(Object? v, String path) {
  if (v is num) return v.toDouble();
  throw ApiShapeError(path, 'expected a number, got ${v.runtimeType}');
}

/// RFC3339 with nanoseconds. DateTime keeps microseconds, so the last three
/// digits are dropped; everything here is for display, never for equality.
DateTime _time(Object? v, String path) {
  final s = _str(v, path);
  final t = DateTime.tryParse(s);
  if (t == null) {
    throw ApiShapeError(path, 'expected an RFC3339 timestamp, got "$s"');
  }
  return t.toUtc();
}

/// A value the contract itself declares as more than one scalar type.
Object? _any(Object? v, String path) => v;

/// Lets a reader stand in for an element that may be null.
///
/// A null inside a list is not a missing field: an OQL time series writes one
/// for a bucket with no data, and reading it with the plain number reader threw
/// where the contract says null is expected.
T? Function(Object?, String) _nullable<T>(T Function(Object?, String) read) =>
    (v, p) => v == null ? null : read(v, p);

List<T> _list<T>(Object? v, String path, T Function(Object?, String) read) {
  if (v is! List) {
    throw ApiShapeError(path, 'expected an array, got ${v.runtimeType}');
  }
  return List<T>.generate(
    v.length,
    (i) => read(v[i], '$path[$i]'),
    growable: false,
  );
}

Map<String, T> _map<T>(
  Object? v,
  String path,
  T Function(Object?, String) read,
) {
  final m = _obj(v, path);
  return {for (final e in m.entries) e.key: read(e.value, '$path.${e.key}')};
}

/// AuthConfigMode of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum AuthConfigMode {
  postgres('postgres'),
  static('static'),
  unknown('');

  const AuthConfigMode(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static AuthConfigMode fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// AuthConfigCaptchaProvider of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum AuthConfigCaptchaProvider {
  turnstile('turnstile'),
  hcaptcha('hcaptcha'),
  unknown('');

  const AuthConfigCaptchaProvider(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static AuthConfigCaptchaProvider fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// MeAuth of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum MeAuth {
  session('session'),
  apiKey('api_key'),
  licenseKey('license_key'),
  device('device'),
  unknown('');

  const MeAuth(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static MeAuth fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// MeApiKeyRole of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum MeApiKeyRole {
  viewer('viewer'),
  member('member'),
  admin('admin'),
  unknown('');

  const MeApiKeyRole(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static MeApiKeyRole fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// Role of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum Role {
  owner('owner'),
  admin('admin'),
  member('member'),
  viewer('viewer'),
  unknown('');

  const Role(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static Role fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// SessionKind of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum SessionKind {
  browser('browser'),
  device('device'),
  unknown('');

  const SessionKind(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static SessionKind fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// AlertRuleType of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum AlertRuleType {
  metricThreshold('metric_threshold'),
  logMatch('log_match'),
  noData('no_data'),
  discovery('discovery'),
  apm('apm'),
  apmNoData('apm_no_data'),
  apmError('apm_error'),
  oql('oql'),
  sloBurn('slo_burn'),
  anomaly('anomaly'),
  unknown('');

  const AlertRuleType(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static AlertRuleType fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// AlertSeverity of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum AlertSeverity {
  critical('critical'),
  warning('warning'),
  info('info'),
  unknown('');

  const AlertSeverity(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static AlertSeverity fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// AlertIncidentState of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum AlertIncidentState {
  open('open'),
  acknowledged('acknowledged'),
  resolved('resolved'),
  unknown('');

  const AlertIncidentState(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static AlertIncidentState fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// AlertResolveReason of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum AlertResolveReason {
  recovered('recovered'),
  manual('manual'),
  noData('no_data'),
  expired('expired'),
  ruleDisabled('rule_disabled'),
  ruleDeleted('rule_deleted'),
  ruleChanged('rule_changed'),
  unknown('');

  const AlertResolveReason(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static AlertResolveReason fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// DashboardVisibility of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum DashboardVisibility {
  org('org'),
  private('private'),
  unknown('');

  const DashboardVisibility(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static DashboardVisibility fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// OqlResultKind of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum OqlResultKind {
  single('single'),
  facets('facets'),
  timeseries('timeseries'),
  histogram('histogram'),
  unknown('');

  const OqlResultKind(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static OqlResultKind fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// UserLanguage of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum UserLanguage {
  auto('auto'),
  en('en'),
  tr('tr'),
  unknown('');

  const UserLanguage(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static UserLanguage fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// DashboardVariableType of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum DashboardVariableType {
  query('query'),
  list('list'),
  text('text'),
  unknown('');

  const DashboardVariableType(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static DashboardVariableType fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// OqlColumnType of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum OqlColumnType {
  number('number'),
  string('string'),
  unknown('');

  const OqlColumnType(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static OqlColumnType fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// DashboardVisualization of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum DashboardVisualization {
  line('line'),
  area('area'),
  bar('bar'),
  table('table'),
  billboard('billboard'),
  pie('pie'),
  heatmap('heatmap'),
  markdown('markdown'),
  unknown('');

  const DashboardVisualization(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static DashboardVisualization fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// DashboardUnit of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum DashboardUnit {
  empty(''),
  number('number'),
  percent('percent'),
  bytes('bytes'),
  bytesPerSec('bytesPerSec'),
  ms('ms'),
  s('s'),
  unknown('');

  const DashboardUnit(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static DashboardUnit fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// DashboardThresholdSeverity of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum DashboardThresholdSeverity {
  warning('warning'),
  critical('critical'),
  unknown('');

  const DashboardThresholdSeverity(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static DashboardThresholdSeverity fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// `AuthConfig` of the openlog API contract.
class AuthConfig {
  const AuthConfig({
    required this.mode,
    required this.signupEnabled,
    required this.passwordMinLength,
    required this.emailEnabled,
    required this.emailVerificationRequired,
    this.captcha,
    this.ssoEnabled,
  });

  factory AuthConfig.fromJson(Object? json, [String path = 'AuthConfig']) {
    final m = _obj(json, path);
    return AuthConfig(
      mode: _req(m, 'mode', path, AuthConfigMode.fromJson),
      signupEnabled: _req(m, 'signup_enabled', path, _bool),
      passwordMinLength: _req(m, 'password_min_length', path, _int),
      emailEnabled: _req(m, 'email_enabled', path, _bool),
      emailVerificationRequired: _req(
        m,
        'email_verification_required',
        path,
        _bool,
      ),
      captcha: _opt(
        m,
        'captcha',
        path,
        (v, p) => AuthConfigCaptcha.fromJson(v, p),
      ),
      ssoEnabled: _opt(m, 'sso_enabled', path, _bool),
    );
  }

  final AuthConfigMode mode;
  final bool signupEnabled;
  final int passwordMinLength;
  final bool emailEnabled;
  final bool emailVerificationRequired;
  final AuthConfigCaptcha? captcha;
  final bool? ssoEnabled;
}

/// `AuthConfigCaptcha` of the openlog API contract.
class AuthConfigCaptcha {
  const AuthConfigCaptcha({required this.provider, required this.siteKey});

  factory AuthConfigCaptcha.fromJson(
    Object? json, [
    String path = 'AuthConfigCaptcha',
  ]) {
    final m = _obj(json, path);
    return AuthConfigCaptcha(
      provider: _req(m, 'provider', path, AuthConfigCaptchaProvider.fromJson),
      siteKey: _req(m, 'site_key', path, _str),
    );
  }

  final AuthConfigCaptchaProvider provider;
  final String siteKey;
}

/// `Me` of the openlog API contract.
class Me {
  const Me({
    required this.auth,
    this.user,
    this.apiKey,
    this.organization,
    this.role,
    required this.organizations,
    this.csrfToken,
  });

  factory Me.fromJson(Object? json, [String path = 'Me']) {
    final m = _obj(json, path);
    return Me(
      auth: _req(m, 'auth', path, MeAuth.fromJson),
      user: _opt(m, 'user', path, (v, p) => User.fromJson(v, p)),
      apiKey: _opt(m, 'api_key', path, (v, p) => MeApiKey.fromJson(v, p)),
      organization: _opt(
        m,
        'organization',
        path,
        (v, p) => OrgRef.fromJson(v, p),
      ),
      role: _opt(m, 'role', path, Role.fromJson),
      organizations: _req(
        m,
        'organizations',
        path,
        (v, p) => _list<OrgRef>(v, p, (v, p) => OrgRef.fromJson(v, p)),
      ),
      csrfToken: _opt(m, 'csrf_token', path, _str),
    );
  }

  final MeAuth auth;
  final User? user;
  final MeApiKey? apiKey;
  final OrgRef? organization;
  final Role? role;
  final List<OrgRef> organizations;
  final String? csrfToken;
}

/// `MeApiKey` of the openlog API contract.
class MeApiKey {
  const MeApiKey({required this.id, required this.name, required this.role});

  factory MeApiKey.fromJson(Object? json, [String path = 'MeApiKey']) {
    final m = _obj(json, path);
    return MeApiKey(
      id: _req(m, 'id', path, _str),
      name: _req(m, 'name', path, _str),
      role: _req(m, 'role', path, MeApiKeyRole.fromJson),
    );
  }

  final String id;
  final String name;
  final MeApiKeyRole role;
}

/// `Session` of the openlog API contract.
class Session {
  const Session({
    required this.id,
    required this.createdAt,
    required this.lastSeenAt,
    required this.expiresAt,
    required this.ip,
    required this.userAgent,
    required this.current,
    required this.kind,
    required this.deviceName,
  });

  factory Session.fromJson(Object? json, [String path = 'Session']) {
    final m = _obj(json, path);
    return Session(
      id: _req(m, 'id', path, _str),
      createdAt: _req(m, 'created_at', path, _time),
      lastSeenAt: _req(m, 'last_seen_at', path, _time),
      expiresAt: _req(m, 'expires_at', path, _time),
      ip: _req(m, 'ip', path, _str),
      userAgent: _req(m, 'user_agent', path, _str),
      current: _req(m, 'current', path, _bool),
      kind: _req(m, 'kind', path, SessionKind.fromJson),
      deviceName: _req(m, 'device_name', path, _str),
    );
  }

  final String id;
  final DateTime createdAt;
  final DateTime lastSeenAt;
  final DateTime expiresAt;
  final String ip;
  final String userAgent;
  final bool current;
  final SessionKind kind;
  final String deviceName;
}

/// `AlertIncident` of the openlog API contract.
class AlertIncident {
  const AlertIncident({
    required this.id,
    this.ruleId,
    required this.ruleName,
    required this.ruleType,
    required this.severity,
    required this.state,
    required this.seriesKey,
    required this.labels,
    required this.summary,
    this.value,
    this.lastValue,
    this.threshold,
    required this.flapping,
    required this.muted,
    required this.openedAt,
    this.acknowledgedAt,
    this.acknowledgedByEmail,
    this.resolvedAt,
    this.resolvedByEmail,
    this.resolveReason,
    required this.channelIds,
  });

  factory AlertIncident.fromJson(
    Object? json, [
    String path = 'AlertIncident',
  ]) {
    final m = _obj(json, path);
    return AlertIncident(
      id: _req(m, 'id', path, _str),
      ruleId: _opt(m, 'rule_id', path, _str),
      ruleName: _req(m, 'rule_name', path, _str),
      ruleType: _req(m, 'rule_type', path, AlertRuleType.fromJson),
      severity: _req(m, 'severity', path, AlertSeverity.fromJson),
      state: _req(m, 'state', path, AlertIncidentState.fromJson),
      seriesKey: _req(m, 'series_key', path, _str),
      labels: _req(m, 'labels', path, (v, p) => _map<String>(v, p, _str)),
      summary: _req(m, 'summary', path, _str),
      value: _opt(m, 'value', path, _num),
      lastValue: _opt(m, 'last_value', path, _num),
      threshold: _opt(m, 'threshold', path, _num),
      flapping: _req(m, 'flapping', path, _bool),
      muted: _req(m, 'muted', path, _bool),
      openedAt: _req(m, 'opened_at', path, _time),
      acknowledgedAt: _opt(m, 'acknowledged_at', path, _time),
      acknowledgedByEmail: _opt(m, 'acknowledged_by_email', path, _str),
      resolvedAt: _opt(m, 'resolved_at', path, _time),
      resolvedByEmail: _opt(m, 'resolved_by_email', path, _str),
      resolveReason: _opt(
        m,
        'resolve_reason',
        path,
        AlertResolveReason.fromJson,
      ),
      channelIds: _req(
        m,
        'channel_ids',
        path,
        (v, p) => _list<String>(v, p, _str),
      ),
    );
  }

  final String id;
  final String? ruleId;
  final String ruleName;
  final AlertRuleType ruleType;
  final AlertSeverity severity;
  final AlertIncidentState state;
  final String seriesKey;
  final Map<String, String> labels;
  final String summary;
  final double? value;
  final double? lastValue;
  final double? threshold;
  final bool flapping;
  final bool muted;
  final DateTime openedAt;
  final DateTime? acknowledgedAt;
  final String? acknowledgedByEmail;
  final DateTime? resolvedAt;
  final String? resolvedByEmail;
  final AlertResolveReason? resolveReason;
  final List<String> channelIds;
}

/// `ApmService` of the openlog API contract.
class ApmService {
  const ApmService({
    required this.requests,
    required this.throughput,
    required this.errors,
    required this.errorRate,
    this.avgMs,
    this.p50Ms,
    this.p95Ms,
    this.p99Ms,
    this.apdex,
    required this.serviceName,
    required this.serviceNamespace,
    required this.environment,
    required this.language,
    required this.version,
    required this.lastSeen,
    required this.apdexTMs,
    required this.sparkline,
  });

  factory ApmService.fromJson(Object? json, [String path = 'ApmService']) {
    final m = _obj(json, path);
    return ApmService(
      requests: _req(m, 'requests', path, _num),
      throughput: _req(m, 'throughput', path, _num),
      errors: _req(m, 'errors', path, _num),
      errorRate: _req(m, 'error_rate', path, _num),
      avgMs: _opt(m, 'avg_ms', path, _num),
      p50Ms: _opt(m, 'p50_ms', path, _num),
      p95Ms: _opt(m, 'p95_ms', path, _num),
      p99Ms: _opt(m, 'p99_ms', path, _num),
      apdex: _opt(m, 'apdex', path, _num),
      serviceName: _req(m, 'service_name', path, _str),
      serviceNamespace: _req(m, 'service_namespace', path, _str),
      environment: _req(m, 'environment', path, _str),
      language: _req(m, 'language', path, _str),
      version: _req(m, 'version', path, _str),
      lastSeen: _req(m, 'last_seen', path, _time),
      apdexTMs: _req(m, 'apdex_t_ms', path, _num),
      sparkline: _req(
        m,
        'sparkline',
        path,
        (v, p) =>
            _list<List<double>>(v, p, (v, p) => _list<double>(v, p, _num)),
      ),
    );
  }

  final double requests;
  final double throughput;
  final double errors;
  final double errorRate;
  final double? avgMs;
  final double? p50Ms;
  final double? p95Ms;
  final double? p99Ms;
  final double? apdex;
  final String serviceName;
  final String serviceNamespace;
  final String environment;
  final String language;
  final String version;
  final DateTime lastSeen;
  final double apdexTMs;
  final List<List<double>> sparkline;
}

/// `DashboardSummary` of the openlog API contract.
class DashboardSummary {
  const DashboardSummary({
    required this.id,
    required this.name,
    required this.description,
    required this.visibility,
    required this.pageCount,
    required this.widgetCount,
    required this.createdByEmail,
    required this.updatedAt,
    required this.canEdit,
  });

  factory DashboardSummary.fromJson(
    Object? json, [
    String path = 'DashboardSummary',
  ]) {
    final m = _obj(json, path);
    return DashboardSummary(
      id: _req(m, 'id', path, _str),
      name: _req(m, 'name', path, _str),
      description: _req(m, 'description', path, _str),
      visibility: _req(m, 'visibility', path, DashboardVisibility.fromJson),
      pageCount: _req(m, 'page_count', path, _int),
      widgetCount: _req(m, 'widget_count', path, _int),
      createdByEmail: _req(m, 'created_by_email', path, _str),
      updatedAt: _req(m, 'updated_at', path, _time),
      canEdit: _req(m, 'can_edit', path, _bool),
    );
  }

  final String id;
  final String name;
  final String description;
  final DashboardVisibility visibility;
  final int pageCount;
  final int widgetCount;
  final String createdByEmail;
  final DateTime updatedAt;
  final bool canEdit;
}

/// `Dashboard` of the openlog API contract.
class Dashboard {
  const Dashboard({
    required this.id,
    required this.name,
    required this.description,
    required this.visibility,
    required this.version,
    required this.variables,
    required this.pages,
    this.createdByUserId,
    required this.createdByEmail,
    required this.createdAt,
    required this.updatedAt,
    required this.canEdit,
  });

  factory Dashboard.fromJson(Object? json, [String path = 'Dashboard']) {
    final m = _obj(json, path);
    return Dashboard(
      id: _req(m, 'id', path, _str),
      name: _req(m, 'name', path, _str),
      description: _req(m, 'description', path, _str),
      visibility: _req(m, 'visibility', path, DashboardVisibility.fromJson),
      version: _req(m, 'version', path, _int),
      variables: _req(
        m,
        'variables',
        path,
        (v, p) => _list<DashboardVariable>(
          v,
          p,
          (v, p) => DashboardVariable.fromJson(v, p),
        ),
      ),
      pages: _req(
        m,
        'pages',
        path,
        (v, p) =>
            _list<DashboardPage>(v, p, (v, p) => DashboardPage.fromJson(v, p)),
      ),
      createdByUserId: _opt(m, 'created_by_user_id', path, _str),
      createdByEmail: _req(m, 'created_by_email', path, _str),
      createdAt: _req(m, 'created_at', path, _time),
      updatedAt: _req(m, 'updated_at', path, _time),
      canEdit: _req(m, 'can_edit', path, _bool),
    );
  }

  final String id;
  final String name;
  final String description;
  final DashboardVisibility visibility;
  final int version;
  final List<DashboardVariable> variables;
  final List<DashboardPage> pages;
  final String? createdByUserId;
  final String createdByEmail;
  final DateTime createdAt;
  final DateTime updatedAt;
  final bool canEdit;
}

/// `OqlResult` of the openlog API contract.
class OqlResult {
  const OqlResult({
    required this.kind,
    required this.eventType,
    required this.columns,
    required this.facets,
    required this.rows,
    required this.series,
    required this.buckets,
    this.compare,
    required this.metadata,
  });

  factory OqlResult.fromJson(Object? json, [String path = 'OqlResult']) {
    final m = _obj(json, path);
    return OqlResult(
      kind: _req(m, 'kind', path, OqlResultKind.fromJson),
      eventType: _req(m, 'event_type', path, _str),
      columns: _req(
        m,
        'columns',
        path,
        (v, p) => _list<OqlColumn>(v, p, (v, p) => OqlColumn.fromJson(v, p)),
      ),
      facets: _req(m, 'facets', path, (v, p) => _list<String>(v, p, _str)),
      rows: _req(
        m,
        'rows',
        path,
        (v, p) => _list<OqlRow>(v, p, (v, p) => OqlRow.fromJson(v, p)),
      ),
      series: _req(
        m,
        'series',
        path,
        (v, p) => _list<OqlSeries>(v, p, (v, p) => OqlSeries.fromJson(v, p)),
      ),
      buckets: _req(
        m,
        'buckets',
        path,
        (v, p) => _list<OqlHistogramBucket>(
          v,
          p,
          (v, p) => OqlHistogramBucket.fromJson(v, p),
        ),
      ),
      compare: _opt(m, 'compare', path, (v, p) => OqlCompare.fromJson(v, p)),
      metadata: _req(m, 'metadata', path, (v, p) => OqlMetadata.fromJson(v, p)),
    );
  }

  final OqlResultKind kind;
  final String eventType;
  final List<OqlColumn> columns;
  final List<String> facets;
  final List<OqlRow> rows;
  final List<OqlSeries> series;
  final List<OqlHistogramBucket> buckets;
  final OqlCompare? compare;
  final OqlMetadata metadata;
}

/// `User` of the openlog API contract.
class User {
  const User({
    required this.id,
    required this.email,
    required this.name,
    required this.emailVerified,
    required this.language,
  });

  factory User.fromJson(Object? json, [String path = 'User']) {
    final m = _obj(json, path);
    return User(
      id: _req(m, 'id', path, _str),
      email: _req(m, 'email', path, _str),
      name: _req(m, 'name', path, _str),
      emailVerified: _req(m, 'email_verified', path, _bool),
      language: _req(m, 'language', path, UserLanguage.fromJson),
    );
  }

  final String id;
  final String email;
  final String name;
  final bool emailVerified;
  final UserLanguage language;
}

/// `OrgRef` of the openlog API contract.
class OrgRef {
  const OrgRef({
    required this.id,
    required this.tenantId,
    required this.name,
    this.role,
  });

  factory OrgRef.fromJson(Object? json, [String path = 'OrgRef']) {
    final m = _obj(json, path);
    return OrgRef(
      id: _req(m, 'id', path, _str),
      tenantId: _req(m, 'tenant_id', path, _str),
      name: _req(m, 'name', path, _str),
      role: _opt(m, 'role', path, Role.fromJson),
    );
  }

  final String id;
  final String tenantId;
  final String name;
  final Role? role;
}

/// `DashboardVariable` of the openlog API contract.
class DashboardVariable {
  const DashboardVariable({
    required this.name,
    required this.label,
    required this.type,
    required this.query,
    required this.values,
    required this.defaultValue,
    required this.multi,
    required this.includeAll,
  });

  factory DashboardVariable.fromJson(
    Object? json, [
    String path = 'DashboardVariable',
  ]) {
    final m = _obj(json, path);
    return DashboardVariable(
      name: _req(m, 'name', path, _str),
      label: _req(m, 'label', path, _str),
      type: _req(m, 'type', path, DashboardVariableType.fromJson),
      query: _req(m, 'query', path, _str),
      values: _req(m, 'values', path, (v, p) => _list<String>(v, p, _str)),
      defaultValue: _req(
        m,
        'default',
        path,
        (v, p) => _list<String>(v, p, _str),
      ),
      multi: _req(m, 'multi', path, _bool),
      includeAll: _req(m, 'include_all', path, _bool),
    );
  }

  final String name;
  final String label;
  final DashboardVariableType type;
  final String query;
  final List<String> values;
  final List<String> defaultValue;
  final bool multi;
  final bool includeAll;
}

/// `DashboardPage` of the openlog API contract.
class DashboardPage {
  const DashboardPage({
    required this.id,
    required this.name,
    required this.widgets,
  });

  factory DashboardPage.fromJson(
    Object? json, [
    String path = 'DashboardPage',
  ]) {
    final m = _obj(json, path);
    return DashboardPage(
      id: _req(m, 'id', path, _str),
      name: _req(m, 'name', path, _str),
      widgets: _req(
        m,
        'widgets',
        path,
        (v, p) => _list<DashboardWidget>(
          v,
          p,
          (v, p) => DashboardWidget.fromJson(v, p),
        ),
      ),
    );
  }

  final String id;
  final String name;
  final List<DashboardWidget> widgets;
}

/// `OqlColumn` of the openlog API contract.
class OqlColumn {
  const OqlColumn({
    required this.name,
    required this.function,
    required this.type,
  });

  factory OqlColumn.fromJson(Object? json, [String path = 'OqlColumn']) {
    final m = _obj(json, path);
    return OqlColumn(
      name: _req(m, 'name', path, _str),
      function: _req(m, 'function', path, _str),
      type: _req(m, 'type', path, OqlColumnType.fromJson),
    );
  }

  final String name;
  final String function;
  final OqlColumnType type;
}

/// `OqlRow` of the openlog API contract.
class OqlRow {
  const OqlRow({required this.facets, required this.values});

  factory OqlRow.fromJson(Object? json, [String path = 'OqlRow']) {
    final m = _obj(json, path);
    return OqlRow(
      facets: _req(m, 'facets', path, (v, p) => _list<String>(v, p, _str)),
      values: _req(m, 'values', path, (v, p) => _list<Object?>(v, p, _any)),
    );
  }

  final List<String> facets;
  final List<Object?> values;
}

/// `OqlSeries` of the openlog API contract.
class OqlSeries {
  const OqlSeries({
    required this.facets,
    required this.column,
    required this.points,
  });

  factory OqlSeries.fromJson(Object? json, [String path = 'OqlSeries']) {
    final m = _obj(json, path);
    return OqlSeries(
      facets: _req(m, 'facets', path, (v, p) => _list<String>(v, p, _str)),
      column: _req(m, 'column', path, _int),
      points: _req(
        m,
        'points',
        path,
        (v, p) => _list<List<double?>>(
          v,
          p,
          (v, p) => _list<double?>(v, p, _nullable<double>(_num)),
        ),
      ),
    );
  }

  final List<String> facets;
  final int column;
  final List<List<double?>> points;
}

/// `OqlHistogramBucket` of the openlog API contract.
class OqlHistogramBucket {
  const OqlHistogramBucket({
    required this.from,
    required this.to,
    required this.count,
  });

  factory OqlHistogramBucket.fromJson(
    Object? json, [
    String path = 'OqlHistogramBucket',
  ]) {
    final m = _obj(json, path);
    return OqlHistogramBucket(
      from: _req(m, 'from', path, _num),
      to: _req(m, 'to', path, _num),
      count: _req(m, 'count', path, _num),
    );
  }

  final double from;
  final double to;
  final double count;
}

/// `OqlCompare` of the openlog API contract.
class OqlCompare {
  const OqlCompare({
    required this.offsetSeconds,
    required this.rows,
    required this.series,
    required this.buckets,
  });

  factory OqlCompare.fromJson(Object? json, [String path = 'OqlCompare']) {
    final m = _obj(json, path);
    return OqlCompare(
      offsetSeconds: _req(m, 'offset_seconds', path, _int),
      rows: _req(
        m,
        'rows',
        path,
        (v, p) => _list<OqlRow>(v, p, (v, p) => OqlRow.fromJson(v, p)),
      ),
      series: _req(
        m,
        'series',
        path,
        (v, p) => _list<OqlSeries>(v, p, (v, p) => OqlSeries.fromJson(v, p)),
      ),
      buckets: _req(
        m,
        'buckets',
        path,
        (v, p) => _list<OqlHistogramBucket>(
          v,
          p,
          (v, p) => OqlHistogramBucket.fromJson(v, p),
        ),
      ),
    );
  }

  final int offsetSeconds;
  final List<OqlRow> rows;
  final List<OqlSeries> series;
  final List<OqlHistogramBucket> buckets;
}

/// `OqlMetadata` of the openlog API contract.
class OqlMetadata {
  const OqlMetadata({
    required this.from,
    required this.to,
    this.bucketSeconds,
    required this.rollup,
    required this.table,
    required this.rowsRead,
    required this.bytesRead,
    required this.elapsedMs,
    required this.queries,
    required this.facetLimit,
    required this.truncated,
    required this.warnings,
    this.ignoredFilters,
  });

  factory OqlMetadata.fromJson(Object? json, [String path = 'OqlMetadata']) {
    final m = _obj(json, path);
    return OqlMetadata(
      from: _req(m, 'from', path, _time),
      to: _req(m, 'to', path, _time),
      bucketSeconds: _opt(m, 'bucket_seconds', path, _int),
      rollup: _req(m, 'rollup', path, _bool),
      table: _req(m, 'table', path, _str),
      rowsRead: _req(m, 'rows_read', path, _int),
      bytesRead: _req(m, 'bytes_read', path, _int),
      elapsedMs: _req(m, 'elapsed_ms', path, _int),
      queries: _req(m, 'queries', path, _int),
      facetLimit: _req(m, 'facet_limit', path, _int),
      truncated: _req(m, 'truncated', path, _bool),
      warnings: _req(m, 'warnings', path, (v, p) => _list<String>(v, p, _str)),
      ignoredFilters: _opt(
        m,
        'ignored_filters',
        path,
        (v, p) => _list<String>(v, p, _str),
      ),
    );
  }

  final DateTime from;
  final DateTime to;
  final int? bucketSeconds;
  final bool rollup;
  final String table;
  final int rowsRead;
  final int bytesRead;
  final int elapsedMs;
  final int queries;
  final int facetLimit;
  final bool truncated;
  final List<String> warnings;
  final List<String>? ignoredFilters;
}

/// `DashboardWidget` of the openlog API contract.
class DashboardWidget {
  const DashboardWidget({
    required this.id,
    required this.title,
    required this.visualization,
    required this.layout,
    required this.query,
    required this.markdown,
    required this.unit,
    required this.thresholds,
    required this.options,
  });

  factory DashboardWidget.fromJson(
    Object? json, [
    String path = 'DashboardWidget',
  ]) {
    final m = _obj(json, path);
    return DashboardWidget(
      id: _req(m, 'id', path, _str),
      title: _req(m, 'title', path, _str),
      visualization: _req(
        m,
        'visualization',
        path,
        DashboardVisualization.fromJson,
      ),
      layout: _req(
        m,
        'layout',
        path,
        (v, p) => DashboardWidgetLayout.fromJson(v, p),
      ),
      query: _req(m, 'query', path, _str),
      markdown: _req(m, 'markdown', path, _str),
      unit: _req(m, 'unit', path, DashboardUnit.fromJson),
      thresholds: _req(
        m,
        'thresholds',
        path,
        (v, p) => _list<DashboardThreshold>(
          v,
          p,
          (v, p) => DashboardThreshold.fromJson(v, p),
        ),
      ),
      options: _req(
        m,
        'options',
        path,
        (v, p) => DashboardWidgetOptions.fromJson(v, p),
      ),
    );
  }

  final String id;
  final String title;
  final DashboardVisualization visualization;
  final DashboardWidgetLayout layout;
  final String query;
  final String markdown;
  final DashboardUnit unit;
  final List<DashboardThreshold> thresholds;
  final DashboardWidgetOptions options;
}

/// `DashboardWidgetLayout` of the openlog API contract.
class DashboardWidgetLayout {
  const DashboardWidgetLayout({
    required this.x,
    required this.y,
    required this.w,
    required this.h,
  });

  factory DashboardWidgetLayout.fromJson(
    Object? json, [
    String path = 'DashboardWidgetLayout',
  ]) {
    final m = _obj(json, path);
    return DashboardWidgetLayout(
      x: _req(m, 'x', path, _int),
      y: _req(m, 'y', path, _int),
      w: _req(m, 'w', path, _int),
      h: _req(m, 'h', path, _int),
    );
  }

  final int x;
  final int y;
  final int w;
  final int h;
}

/// `DashboardThreshold` of the openlog API contract.
class DashboardThreshold {
  const DashboardThreshold({required this.value, required this.severity});

  factory DashboardThreshold.fromJson(
    Object? json, [
    String path = 'DashboardThreshold',
  ]) {
    final m = _obj(json, path);
    return DashboardThreshold(
      value: _req(m, 'value', path, _num),
      severity: _req(m, 'severity', path, DashboardThresholdSeverity.fromJson),
    );
  }

  final double value;
  final DashboardThresholdSeverity severity;
}

/// `DashboardWidgetOptions` of the openlog API contract.
class DashboardWidgetOptions {
  const DashboardWidgetOptions({this.stacked, this.legend});

  factory DashboardWidgetOptions.fromJson(
    Object? json, [
    String path = 'DashboardWidgetOptions',
  ]) {
    final m = _obj(json, path);
    return DashboardWidgetOptions(
      stacked: _opt(m, 'stacked', path, _bool),
      legend: _opt(m, 'legend', path, _bool),
    );
  }

  final bool? stacked;
  final bool? legend;
}

/// `DeviceSession` of the openlog API contract.
class DeviceSession {
  const DeviceSession({
    required this.token,
    required this.sessionId,
    required this.expiresAt,
    required this.me,
  });

  factory DeviceSession.fromJson(
    Object? json, [
    String path = 'DeviceSession',
  ]) {
    final m = _obj(json, path);
    return DeviceSession(
      token: _req(m, 'token', path, _str),
      sessionId: _req(m, 'session_id', path, _str),
      expiresAt: _req(m, 'expires_at', path, _time),
      me: _req(m, 'me', path, (v, p) => Me.fromJson(v, p)),
    );
  }

  final String token;
  final String sessionId;
  final DateTime expiresAt;
  final Me me;
}

/// `IncidentPage` of the openlog API contract.
class IncidentPage {
  const IncidentPage({
    required this.incidents,
    this.nextCursor,
    required this.counts,
  });

  factory IncidentPage.fromJson(Object? json, [String path = 'IncidentPage']) {
    final m = _obj(json, path);
    return IncidentPage(
      incidents: _req(
        m,
        'incidents',
        path,
        (v, p) =>
            _list<AlertIncident>(v, p, (v, p) => AlertIncident.fromJson(v, p)),
      ),
      nextCursor: _opt(m, 'next_cursor', path, _str),
      counts: _req(
        m,
        'counts',
        path,
        (v, p) => IncidentPageCounts.fromJson(v, p),
      ),
    );
  }

  final List<AlertIncident> incidents;
  final String? nextCursor;
  final IncidentPageCounts counts;
}

/// All incidents of the organization by state (resolved = last 7 days)
class IncidentPageCounts {
  const IncidentPageCounts({
    required this.open,
    required this.acknowledged,
    required this.resolved,
  });

  factory IncidentPageCounts.fromJson(
    Object? json, [
    String path = 'IncidentPageCounts',
  ]) {
    final m = _obj(json, path);
    return IncidentPageCounts(
      open: _req(m, 'open', path, _int),
      acknowledged: _req(m, 'acknowledged', path, _int),
      resolved: _req(m, 'resolved', path, _int),
    );
  }

  final int open;
  final int acknowledged;
  final int resolved;
}

/// `ServicePage` of the openlog API contract.
class ServicePage {
  const ServicePage({required this.step, required this.services});

  factory ServicePage.fromJson(Object? json, [String path = 'ServicePage']) {
    final m = _obj(json, path);
    return ServicePage(
      step: _req(m, 'step', path, _str),
      services: _req(
        m,
        'services',
        path,
        (v, p) => _list<ApmService>(v, p, (v, p) => ApmService.fromJson(v, p)),
      ),
    );
  }

  final String step;
  final List<ApmService> services;
}

/// `LogPage` of the openlog API contract.
class LogPage {
  const LogPage({required this.logs, this.nextCursor});

  factory LogPage.fromJson(Object? json, [String path = 'LogPage']) {
    final m = _obj(json, path);
    return LogPage(
      logs: _req(
        m,
        'logs',
        path,
        (v, p) => _list<LogRecord>(v, p, (v, p) => LogRecord.fromJson(v, p)),
      ),
      nextCursor: _opt(m, 'next_cursor', path, _str),
    );
  }

  final List<LogRecord> logs;
  final String? nextCursor;
}

/// `DashboardPageList` of the openlog API contract.
class DashboardPageList {
  const DashboardPageList({required this.dashboards});

  factory DashboardPageList.fromJson(
    Object? json, [
    String path = 'DashboardPageList',
  ]) {
    final m = _obj(json, path);
    return DashboardPageList(
      dashboards: _req(
        m,
        'dashboards',
        path,
        (v, p) => _list<DashboardSummary>(
          v,
          p,
          (v, p) => DashboardSummary.fromJson(v, p),
        ),
      ),
    );
  }

  final List<DashboardSummary> dashboards;
}

/// `LogRecord` of the openlog API contract.
class LogRecord {
  const LogRecord({
    required this.timestamp,
    required this.severityText,
    required this.severityNumber,
    required this.body,
    required this.hostId,
    required this.serviceName,
    required this.traceId,
    required this.spanId,
    required this.attributes,
    required this.resourceAttributes,
  });

  factory LogRecord.fromJson(Object? json, [String path = 'LogRecord']) {
    final m = _obj(json, path);
    return LogRecord(
      timestamp: _req(m, 'timestamp', path, _time),
      severityText: _req(m, 'severity_text', path, _str),
      severityNumber: _req(m, 'severity_number', path, _int),
      body: _req(m, 'body', path, _str),
      hostId: _req(m, 'host_id', path, _str),
      serviceName: _req(m, 'service_name', path, _str),
      traceId: _req(m, 'trace_id', path, _str),
      spanId: _req(m, 'span_id', path, _str),
      attributes: _req(
        m,
        'attributes',
        path,
        (v, p) => _map<String>(v, p, _str),
      ),
      resourceAttributes: _req(
        m,
        'resource_attributes',
        path,
        (v, p) => _map<String>(v, p, _str),
      ),
    );
  }

  final DateTime timestamp;
  final String severityText;
  final int severityNumber;
  final String body;
  final String hostId;
  final String serviceName;
  final String traceId;
  final String spanId;
  final Map<String, String> attributes;
  final Map<String, String> resourceAttributes;
}
