// GENERATED by tool/gen_api.dart from docs/contracts/openapi.yaml. Do not edit.
//
// Regenerate with: dart run tool/gen_api.dart
// CI fails when this file and the contract disagree (dart run tool/gen_api.dart --check).

// ignore_for_file: lines_longer_than_80_chars, unused_element

/// Thrown when the server sends a body this build cannot read: a required field
/// is missing or has the wrong shape. It names the field, because "unexpected
/// null" three screens later is how a contract break turns into a bug report
/// about something else.
class ApiShapeError implements Exception {
  ApiShapeError(this.path, this.detail);

  final String path;
  final String detail;

  @override
  String toString() =>
      'the server sent something this app cannot read at "$path": $detail';
}

Map<String, Object?> _obj(Object? v, String path) {
  if (v is Map) return v.cast<String, Object?>();
  throw ApiShapeError(path, 'expected an object, got ${v.runtimeType}');
}

T _req<T>(
  Map<String, Object?> m,
  String key,
  String path,
  T Function(Object?, String) read,
) {
  if (!m.containsKey(key) || m[key] == null) {
    throw ApiShapeError('$path.$key', 'required field is missing');
  }
  return read(m[key], '$path.$key');
}

T? _opt<T>(
  Map<String, Object?> m,
  String key,
  String path,
  T Function(Object?, String) read,
) {
  final v = m[key];
  return v == null ? null : read(v, '$path.$key');
}

String _str(Object? v, String path) {
  if (v is String) return v;
  throw ApiShapeError(path, 'expected a string, got ${v.runtimeType}');
}

bool _bool(Object? v, String path) {
  if (v is bool) return v;
  throw ApiShapeError(path, 'expected a boolean, got ${v.runtimeType}');
}

int _int(Object? v, String path) {
  if (v is int) return v;
  if (v is num && v == v.roundToDouble()) return v.toInt();
  throw ApiShapeError(path, 'expected an integer, got ${v.runtimeType}');
}

double _num(Object? v, String path) {
  if (v is num) return v.toDouble();
  throw ApiShapeError(path, 'expected a number, got ${v.runtimeType}');
}

/// RFC3339 with nanoseconds. DateTime keeps microseconds, so the last three
/// digits are dropped; everything here is for display, never for equality.
DateTime _time(Object? v, String path) {
  final s = _str(v, path);
  final t = DateTime.tryParse(s);
  if (t == null) {
    throw ApiShapeError(path, 'expected an RFC3339 timestamp, got "$s"');
  }
  return t.toUtc();
}

List<T> _list<T>(Object? v, String path, T Function(Object?, String) read) {
  if (v is! List) {
    throw ApiShapeError(path, 'expected an array, got ${v.runtimeType}');
  }
  return List<T>.generate(
    v.length,
    (i) => read(v[i], '$path[$i]'),
    growable: false,
  );
}

Map<String, T> _map<T>(
  Object? v,
  String path,
  T Function(Object?, String) read,
) {
  final m = _obj(v, path);
  return {for (final e in m.entries) e.key: read(e.value, '$path.${e.key}')};
}

/// AuthConfigMode of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum AuthConfigMode {
  postgres('postgres'),
  static('static'),
  unknown('');

  const AuthConfigMode(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static AuthConfigMode fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// AuthConfigCaptchaProvider of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum AuthConfigCaptchaProvider {
  turnstile('turnstile'),
  hcaptcha('hcaptcha'),
  unknown('');

  const AuthConfigCaptchaProvider(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static AuthConfigCaptchaProvider fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// MeAuth of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum MeAuth {
  session('session'),
  apiKey('api_key'),
  licenseKey('license_key'),
  device('device'),
  unknown('');

  const MeAuth(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static MeAuth fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// MeApiKeyRole of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum MeApiKeyRole {
  viewer('viewer'),
  member('member'),
  admin('admin'),
  unknown('');

  const MeApiKeyRole(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static MeApiKeyRole fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// Role of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum Role {
  owner('owner'),
  admin('admin'),
  member('member'),
  viewer('viewer'),
  unknown('');

  const Role(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static Role fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// SessionKind of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum SessionKind {
  browser('browser'),
  device('device'),
  unknown('');

  const SessionKind(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static SessionKind fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// UserLanguage of the contract.
///
/// `unknown` is not in the contract: it is what a value this build has never
/// heard of becomes. A store build cannot be updated in step with the server it
/// talks to, so a value added there must leave this app readable rather than
/// throwing on a screen that would otherwise have worked.
enum UserLanguage {
  auto('auto'),
  en('en'),
  tr('tr'),
  unknown('');

  const UserLanguage(this.wire);

  /// The value as the API spells it; empty for unknown.
  final String wire;

  static UserLanguage fromJson(Object? v, String path) {
    final s = _str(v, path);
    for (final e in values) {
      if (e.wire == s) return e;
    }
    return unknown;
  }
}

/// `AuthConfig` of the openlog API contract.
class AuthConfig {
  const AuthConfig({
    required this.mode,
    required this.signupEnabled,
    required this.passwordMinLength,
    required this.emailEnabled,
    required this.emailVerificationRequired,
    this.captcha,
    this.ssoEnabled,
  });

  factory AuthConfig.fromJson(Object? json, [String path = 'AuthConfig']) {
    final m = _obj(json, path);
    return AuthConfig(
      mode: _req(m, 'mode', path, AuthConfigMode.fromJson),
      signupEnabled: _req(m, 'signup_enabled', path, _bool),
      passwordMinLength: _req(m, 'password_min_length', path, _int),
      emailEnabled: _req(m, 'email_enabled', path, _bool),
      emailVerificationRequired: _req(
        m,
        'email_verification_required',
        path,
        _bool,
      ),
      captcha: _opt(
        m,
        'captcha',
        path,
        (v, p) => AuthConfigCaptcha.fromJson(v, p),
      ),
      ssoEnabled: _opt(m, 'sso_enabled', path, _bool),
    );
  }

  final AuthConfigMode mode;
  final bool signupEnabled;
  final int passwordMinLength;
  final bool emailEnabled;
  final bool emailVerificationRequired;
  final AuthConfigCaptcha? captcha;
  final bool? ssoEnabled;
}

/// `AuthConfigCaptcha` of the openlog API contract.
class AuthConfigCaptcha {
  const AuthConfigCaptcha({required this.provider, required this.siteKey});

  factory AuthConfigCaptcha.fromJson(
    Object? json, [
    String path = 'AuthConfigCaptcha',
  ]) {
    final m = _obj(json, path);
    return AuthConfigCaptcha(
      provider: _req(m, 'provider', path, AuthConfigCaptchaProvider.fromJson),
      siteKey: _req(m, 'site_key', path, _str),
    );
  }

  final AuthConfigCaptchaProvider provider;
  final String siteKey;
}

/// `Me` of the openlog API contract.
class Me {
  const Me({
    required this.auth,
    this.user,
    this.apiKey,
    this.organization,
    this.role,
    required this.organizations,
    this.csrfToken,
  });

  factory Me.fromJson(Object? json, [String path = 'Me']) {
    final m = _obj(json, path);
    return Me(
      auth: _req(m, 'auth', path, MeAuth.fromJson),
      user: _opt(m, 'user', path, (v, p) => User.fromJson(v, p)),
      apiKey: _opt(m, 'api_key', path, (v, p) => MeApiKey.fromJson(v, p)),
      organization: _opt(
        m,
        'organization',
        path,
        (v, p) => OrgRef.fromJson(v, p),
      ),
      role: _opt(m, 'role', path, Role.fromJson),
      organizations: _req(
        m,
        'organizations',
        path,
        (v, p) => _list<OrgRef>(v, p, (v, p) => OrgRef.fromJson(v, p)),
      ),
      csrfToken: _opt(m, 'csrf_token', path, _str),
    );
  }

  final MeAuth auth;
  final User? user;
  final MeApiKey? apiKey;
  final OrgRef? organization;
  final Role? role;
  final List<OrgRef> organizations;
  final String? csrfToken;
}

/// `MeApiKey` of the openlog API contract.
class MeApiKey {
  const MeApiKey({required this.id, required this.name, required this.role});

  factory MeApiKey.fromJson(Object? json, [String path = 'MeApiKey']) {
    final m = _obj(json, path);
    return MeApiKey(
      id: _req(m, 'id', path, _str),
      name: _req(m, 'name', path, _str),
      role: _req(m, 'role', path, MeApiKeyRole.fromJson),
    );
  }

  final String id;
  final String name;
  final MeApiKeyRole role;
}

/// `Session` of the openlog API contract.
class Session {
  const Session({
    required this.id,
    required this.createdAt,
    required this.lastSeenAt,
    required this.expiresAt,
    required this.ip,
    required this.userAgent,
    required this.current,
    required this.kind,
    required this.deviceName,
  });

  factory Session.fromJson(Object? json, [String path = 'Session']) {
    final m = _obj(json, path);
    return Session(
      id: _req(m, 'id', path, _str),
      createdAt: _req(m, 'created_at', path, _time),
      lastSeenAt: _req(m, 'last_seen_at', path, _time),
      expiresAt: _req(m, 'expires_at', path, _time),
      ip: _req(m, 'ip', path, _str),
      userAgent: _req(m, 'user_agent', path, _str),
      current: _req(m, 'current', path, _bool),
      kind: _req(m, 'kind', path, SessionKind.fromJson),
      deviceName: _req(m, 'device_name', path, _str),
    );
  }

  final String id;
  final DateTime createdAt;
  final DateTime lastSeenAt;
  final DateTime expiresAt;
  final String ip;
  final String userAgent;
  final bool current;
  final SessionKind kind;
  final String deviceName;
}

/// `User` of the openlog API contract.
class User {
  const User({
    required this.id,
    required this.email,
    required this.name,
    required this.emailVerified,
    required this.language,
  });

  factory User.fromJson(Object? json, [String path = 'User']) {
    final m = _obj(json, path);
    return User(
      id: _req(m, 'id', path, _str),
      email: _req(m, 'email', path, _str),
      name: _req(m, 'name', path, _str),
      emailVerified: _req(m, 'email_verified', path, _bool),
      language: _req(m, 'language', path, UserLanguage.fromJson),
    );
  }

  final String id;
  final String email;
  final String name;
  final bool emailVerified;
  final UserLanguage language;
}

/// `OrgRef` of the openlog API contract.
class OrgRef {
  const OrgRef({
    required this.id,
    required this.tenantId,
    required this.name,
    this.role,
  });

  factory OrgRef.fromJson(Object? json, [String path = 'OrgRef']) {
    final m = _obj(json, path);
    return OrgRef(
      id: _req(m, 'id', path, _str),
      tenantId: _req(m, 'tenant_id', path, _str),
      name: _req(m, 'name', path, _str),
      role: _opt(m, 'role', path, Role.fromJson),
    );
  }

  final String id;
  final String tenantId;
  final String name;
  final Role? role;
}

/// `DeviceSession` of the openlog API contract.
class DeviceSession {
  const DeviceSession({
    required this.token,
    required this.sessionId,
    required this.expiresAt,
    required this.me,
  });

  factory DeviceSession.fromJson(
    Object? json, [
    String path = 'DeviceSession',
  ]) {
    final m = _obj(json, path);
    return DeviceSession(
      token: _req(m, 'token', path, _str),
      sessionId: _req(m, 'session_id', path, _str),
      expiresAt: _req(m, 'expires_at', path, _time),
      me: _req(m, 'me', path, (v, p) => Me.fromJson(v, p)),
    );
  }

  final String token;
  final String sessionId;
  final DateTime expiresAt;
  final Me me;
}
