/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hosts seen in the last 24h, ordered by host_name */
        get: operations["listHosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/{host_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMetricNames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/{host_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Time series of one metric on one host. `rate` = per-second increase per series per step (counter resets
         *     clamp to 0), then summed across merged series. Ranges longer than 6h read from the 1-minute rollup.
         *     A host id without a host record in the caller's organization (unknown, or another organization's host)
         *     returns 404. An unknown metric on a known host returns 200 with empty `series` and empty
         *     `metric.type`/`metric.unit`.
         */
        get: operations["getHostMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/{host_id}/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Items of the host's latest complete snapshot. A known host without a complete snapshot returns 200 with
         *     `snapshot_id: ""`, `snapshot_time: null` and empty `items`. A host id without a host record in the
         *     caller's organization returns 404.
         */
        get: operations["getHostInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/{host_id}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Shortcut for `category=discovered_service`; `data` is the discovered service body. Unknown host → 404. */
        get: operations["getHostServices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Items in `category` whose key contains `q` (case-insensitive) across all hosts' latest snapshots, ordered by key then host. */
        get: operations["searchInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Excludes inventory events. `q` is a case-insensitive substring match on body. Newest first.
         *     `attr.<key>=<value>` parameters are exact-match filters on log record attributes; only the keys listed
         *     below are accepted (any other `attr.*` key, an empty or repeated value, or a value over 1024 bytes → 400).
         *     Infra agent log records have an empty `service_name`; filter them with `host_id` and these attributes.
         */
        get: operations["listLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backend version, newest available release and updater status
         * @description Any authenticated principal (both auth modes). Every API, ingest and admin response also carries
         *     `X-Openlog-Version`. The release check runs on one api pod at most every 24 h and verifies the signed
         *     index (docs/contracts/releases-updates.md §5).
         */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Sets the `openlog_session` cookie (HttpOnly, SameSite=Strict, Path=/api). */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Only when OPENLOG_SIGNUP_ENABLED=true. Creates a user and a new organization they own. */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Revokes the user's other sessions. */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentOrg"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["renameCurrentOrg"];
        trace?: never;
    };
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Removes a member; any member may remove themselves (leave). */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        patch: operations["updateMemberRole"];
        trace?: never;
    };
    "/api/v1/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInvitations"];
        put?: never;
        post: operations["createInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["lookupInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description New users choose a password; existing users must send their current password. Signs in. */
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/license-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLicenseKeys"];
        put?: never;
        post: operations["createLicenseKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/license-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Idempotent. Ingest keeps accepting the key for up to OPENLOG_AUTH_CACHE_TTL. */
        delete: operations["revokeLicenseKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAPIKeys"];
        put?: never;
        post: operations["createAPIKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeAPIKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleet/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFleetPolicy"];
        /** @description Admin or owner. Ingest applies the change within OPENLOG_FLEET_POLICY_CACHE_TTL. */
        put: operations["putFleetPolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleet/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFleetSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleet/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFleetHosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleet/hosts/{host_id}/override": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                host_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["putFleetHostOverride"];
        post?: never;
        /** @description Idempotent. */
        delete: operations["deleteFleetHostOverride"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleet/rollouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFleetRollouts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleet/rollouts/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pauseFleetRollout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleet/rollouts/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Paused or halted rollouts. Restarts the soak time; failures of a halted rollout are acknowledged. */
        post: operations["resumeFleetRollout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleet/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createFleetRollback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @enum {string} */
                code: "invalid_argument" | "unauthenticated" | "permission_denied" | "not_found" | "already_exists" | "failed_precondition" | "resource_exhausted" | "internal" | "unavailable" | "timeout";
                message: string;
            };
        };
        /**
         * Format: date-time
         * @description RFC3339 with nanoseconds, UTC (e.g. 2026-09-13T10:00:00.000000000Z)
         */
        Timestamp: string;
        StringMap: {
            [key: string]: string;
        };
        Host: {
            host_id: string;
            host_name: string;
            os_description: string;
            arch: string;
            agent_version: string;
            last_seen: components["schemas"]["Timestamp"];
            resource_attributes: components["schemas"]["StringMap"];
        };
        /**
         * @description Empty string when the metric has no data in range.
         * @enum {string}
         */
        MetricType: "gauge" | "sum" | "histogram" | "exponential_histogram" | "summary" | "";
        MetricMeta: {
            name: string;
            type: components["schemas"]["MetricType"];
            unit: string;
        };
        /** @enum {string} */
        Aggregation: "avg" | "min" | "max" | "sum" | "last" | "rate";
        /** @description [unix milliseconds, value] */
        MetricPoint: [
            number,
            number
        ];
        MetricSeries: {
            attributes: components["schemas"]["StringMap"];
            points: components["schemas"]["MetricPoint"][];
        };
        MetricSeriesResponse: {
            metric: components["schemas"]["MetricMeta"];
            /** @description Whole seconds, e.g. 60s */
            step: string;
            series: components["schemas"]["MetricSeries"][];
        };
        /**
         * @description Known categories (semantic-conventions §3.3); the API accepts any string.
         * @example os
         * @example hardware
         * @example kernel_module
         * @example package
         * @example systemd_unit
         * @example listening_port
         * @example process
         * @example user
         * @example network_interface
         * @example mount
         * @example discovered_service
         */
        InventoryCategory: string;
        InventoryItem: {
            category: string;
            key: string;
            /** @description The category's JSON body; non-JSON bodies are returned as a string. */
            data: unknown;
        };
        InventoryResponse: {
            snapshot_id: string;
            snapshot_time: components["schemas"]["Timestamp"] | null;
            items: components["schemas"]["InventoryItem"][];
        };
        InventorySearchItem: components["schemas"]["InventoryItem"] & {
            host_id: string;
            /** @description Omitted when the host is not found in the hosts table. */
            host_name?: string;
        };
        /** @description Body of `discovered_service` items (semantic-conventions §3.4). Unknown fields must be ignored; any field may be missing. */
        DiscoveredService: {
            rule_id?: string;
            name?: string;
            category?: string;
            instance?: string;
            /** @description Name of the running process (e.g. `redis-server`) when it differs from what `instance` (the executable path) suggests. Optional; older agents omit it. */
            command?: string;
            version?: string;
            matched_by?: string[];
            pids?: number[];
            ports?: {
                protocol?: string;
                address?: string;
                port?: number;
            }[];
            systemd_units?: string[];
            packages?: string[];
            container_ids?: string[];
            integration?: {
                id?: string;
                /** @enum {string} */
                status?: "enabled" | "needs_configuration" | "not_available";
            };
            apm_hint?: null | {
                language?: string;
                agent?: string;
            };
        };
        LogRecord: {
            timestamp: components["schemas"]["Timestamp"];
            severity_text: string;
            severity_number: number;
            body: string;
            host_id: string;
            service_name: string;
            /** @description 32 lowercase hex characters or empty */
            trace_id: string;
            /** @description 16 lowercase hex characters or empty */
            span_id: string;
            attributes: components["schemas"]["StringMap"];
            resource_attributes: components["schemas"]["StringMap"];
        };
        /** @enum {string} */
        SpanKind: "unspecified" | "internal" | "server" | "client" | "producer" | "consumer";
        /** @enum {string} */
        SpanStatusCode: "unset" | "ok" | "error";
        SpanEvent: {
            /** @description RFC3339 with nanoseconds; empty if missing */
            timestamp: string;
            name: string;
            attributes: components["schemas"]["StringMap"];
        };
        Span: {
            span_id: string;
            /** @description Empty for root spans */
            parent_span_id: string;
            name: string;
            kind: components["schemas"]["SpanKind"];
            service_name: string;
            start: components["schemas"]["Timestamp"];
            duration_ns: number;
            status_code: components["schemas"]["SpanStatusCode"];
            status_message: string;
            attributes: components["schemas"]["StringMap"];
            resource_attributes: components["schemas"]["StringMap"];
            events: components["schemas"]["SpanEvent"][];
        };
        Trace: {
            trace_id: string;
            spans: components["schemas"]["Span"][];
        };
        /** @enum {string} */
        Role: "owner" | "admin" | "member" | "viewer";
        NullableTimestamp: components["schemas"]["Timestamp"] | null;
        AuthConfig: {
            /** @enum {string} */
            mode: "postgres" | "static";
            signup_enabled: boolean;
            password_min_length: number;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        SignupRequest: {
            email: string;
            password: string;
            name?: string;
            organization_name: string;
        };
        PasswordChangeRequest: {
            current_password: string;
            new_password: string;
        };
        NameRequest: {
            name: string;
        };
        User: {
            id: string;
            email: string;
            name: string;
        };
        VersionInfo: {
            /**
             * @description SemVer product version; dev builds 0.0.0-dev+<commit>
             * @example 0.9.1
             */
            version: string;
            commit: string;
            /** @description Build time (RFC3339) or empty */
            date: string;
            /** @description Newest verified release of OPENLOG_UPDATE_CHANNEL when newer than this pod; null otherwise. */
            latest_available: components["schemas"]["AvailableRelease"] | null;
            /** @enum {string} */
            update_check: "enabled" | "disabled" | "failed";
            /** @description Status reported by openlog-updater (null when no updater runs). See docs/operations/upgrading.md. */
            updater: components["schemas"]["UpdaterStatus"] | null;
        };
        AvailableRelease: {
            /** @example 0.9.2 */
            version: string;
            notes_url: string;
            /** Format: date-time */
            checked_at: string;
        };
        UpdaterStatus: {
            /** @enum {string} */
            engine: "compose" | "kubernetes";
            /** @enum {string} */
            mode: "off" | "notify" | "auto";
            /** @enum {string} */
            state: "off" | "error" | "up_to_date" | "available" | "waiting_for_maintenance_window" | "updating" | "succeeded" | "failed" | "rolled_back" | "rollback_failed";
            message?: string;
            error?: string;
            current_version?: string;
            target_version?: string;
            previous_version?: string;
            notes_url?: string;
            /** Format: date-time */
            checked_at: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
            backup_file?: string;
            steps?: {
                /** @description backup, pull, migrate, recreate / rollout, health, rollback, cleanup, contract-migrate */
                name: string;
                /** @enum {string} */
                status: "running" | "ok" | "failed";
                detail?: string;
                /** Format: date-time */
                started_at: string;
                /** Format: date-time */
                finished_at?: string;
            }[];
            failed_versions?: string[];
            history?: {
                from: string;
                to: string;
                result: string;
                error?: string;
                /** Format: date-time */
                at: string;
            }[];
        };
        OrgRef: {
            id: string;
            tenant_id: string;
            name: string;
            role?: components["schemas"]["Role"];
        };
        Me: {
            /** @enum {string} */
            auth: "session" | "api_key" | "license_key";
            user: components["schemas"]["User"] | null;
            /** @description The organization of this request (X-Openlog-Org-Id or the default one); null without memberships. */
            organization: components["schemas"]["OrgRef"] | null;
            role: components["schemas"]["Role"] | null;
            organizations: components["schemas"]["OrgRef"][];
            /** @description Send as X-CSRF-Token on mutating cookie-authenticated requests. Null for API keys. */
            csrf_token: string | null;
        };
        Organization: {
            id: string;
            tenant_id: string;
            name: string;
            role: components["schemas"]["Role"];
            created_at: components["schemas"]["Timestamp"];
        };
        Member: {
            user_id: string;
            email: string;
            name: string;
            role: components["schemas"]["Role"];
            joined_at: components["schemas"]["Timestamp"];
        };
        Invitation: {
            id: string;
            email: string;
            role: components["schemas"]["Role"];
            invited_by_email: string;
            created_at: components["schemas"]["Timestamp"];
            expires_at: components["schemas"]["Timestamp"];
        };
        InvitationLookup: {
            organization_name: string;
            email: string;
            role: components["schemas"]["Role"];
            expires_at: components["schemas"]["Timestamp"];
            /** @description true: sign in with the existing password to accept */
            user_exists: boolean;
        };
        LicenseKey: {
            id: string;
            name: string;
            /** @description Visible, non-secret start of the key, e.g. olk_1a2b3c4d */
            prefix: string;
            created_by_email: string;
            created_at: components["schemas"]["Timestamp"];
            last_used_at: components["schemas"]["NullableTimestamp"];
            revoked_at: components["schemas"]["NullableTimestamp"];
        };
        APIKey: {
            id: string;
            name: string;
            prefix: string;
            /** @enum {string} */
            scope: "read";
            created_by_user_id: string;
            created_by_email: string;
            created_at: components["schemas"]["Timestamp"];
            last_used_at: components["schemas"]["NullableTimestamp"];
            expires_at: components["schemas"]["NullableTimestamp"];
            revoked_at: components["schemas"]["NullableTimestamp"];
        };
        Session: {
            id: string;
            created_at: components["schemas"]["Timestamp"];
            last_seen_at: components["schemas"]["Timestamp"];
            expires_at: components["schemas"]["Timestamp"];
            ip: string;
            user_agent: string;
            current: boolean;
        };
        AuditEvent: {
            id: number;
            actor_email: string;
            action: string;
            target_type: string;
            target_id: string;
            details: {
                [key: string]: unknown;
            };
            ip: string;
            created_at: components["schemas"]["Timestamp"];
        };
        /** @enum {string} */
        FleetMode: "off" | "notify" | "auto";
        /** @enum {string} */
        FleetChannel: "stable" | "beta";
        /** @enum {string} */
        FleetTarget: "latest" | "patch" | "pinned";
        /** @enum {string} */
        FleetUpdateState: "idle" | "downloading" | "verifying" | "staged" | "restarting" | "confirming" | "succeeded" | "failed" | "rolled_back";
        /** @enum {string} */
        FleetRolloutState: "active" | "paused" | "halted" | "completed" | "superseded";
        MaintenanceWindow: {
            /** @description Empty = every day */
            days: ("mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun")[];
            /**
             * @description HH:MM UTC
             * @example 02:00
             */
            start: string;
            /**
             * @description HH:MM UTC, 24:00 allowed; end <= start spans midnight
             * @example 05:00
             */
            end: string;
        };
        FleetPolicyInput: {
            mode: components["schemas"]["FleetMode"];
            channel: components["schemas"]["FleetChannel"];
            target: components["schemas"]["FleetTarget"];
            pinned_version?: string | null;
            /** @description Strictly increasing percentages, last = 100 */
            waves: number[];
            wave_soak_minutes: number;
            halt_failure_rate: number;
            maintenance_windows: components["schemas"]["MaintenanceWindow"][];
        };
        FleetPolicy: {
            mode: components["schemas"]["FleetMode"];
            channel: components["schemas"]["FleetChannel"];
            target: components["schemas"]["FleetTarget"];
            pinned_version: string | null;
            waves: number[];
            wave_soak_minutes: number;
            halt_failure_rate: number;
            maintenance_windows: components["schemas"]["MaintenanceWindow"][];
            is_default: boolean;
            updated_at: components["schemas"]["NullableTimestamp"];
            updated_by_email: string;
        };
        FleetRolloutCounters: {
            pending: number;
            attempted: number;
            succeeded: number;
            failed: number;
            rolled_back: number;
        };
        FleetRollout: {
            id: string;
            /** @enum {string} */
            action: "upgrade" | "rollback";
            from_version: string | null;
            /** @description null for target=patch rollouts (see targets) */
            to_version: string | null;
            /** @description target=patch: "major.minor" → version */
            targets: {
                [key: string]: string;
            };
            waves: number[];
            current_wave: number;
            wave_percent: number;
            wave_started_at: components["schemas"]["Timestamp"];
            next_wave_at: components["schemas"]["NullableTimestamp"];
            wave_soak_minutes: number;
            halt_failure_rate: number;
            state: components["schemas"]["FleetRolloutState"];
            state_reason: string;
            counters: components["schemas"]["FleetRolloutCounters"];
            /** @description null = rollout controller */
            created_by_email: string | null;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
            ended_at: components["schemas"]["NullableTimestamp"];
        };
        FleetReleaseInfo: {
            version: string;
            channel: components["schemas"]["FleetChannel"];
            released_at: components["schemas"]["Timestamp"];
            notes_url: string;
        };
        FleetCatalogStatus: {
            /** @enum {string} */
            status: "ok" | "pending" | "error" | "disabled";
            source: string;
            checked_at: components["schemas"]["NullableTimestamp"];
            last_success_at: components["schemas"]["NullableTimestamp"];
            error: string;
            releases: number;
            warnings: string[];
        };
        FleetSummary: {
            total_hosts: number;
            active_hosts: number;
            update_capable: number;
            not_update_capable: {
                /** @description install_method (container */
                reason: string;
                hosts: number;
            }[];
            outdated: number;
            unsupported: number;
            in_progress: number;
            failed: number;
            held: number;
            pinned: number;
            versions: {
                version: string;
                hosts: number;
                latest: boolean;
                outdated: boolean;
                supported: boolean;
            }[];
            latest: {
                stable: components["schemas"]["FleetReleaseInfo"] | null;
                beta: components["schemas"]["FleetReleaseInfo"] | null;
            };
            target: components["schemas"]["FleetReleaseInfo"] | null;
            oldest_supported_version: string;
            policy_mode: components["schemas"]["FleetMode"];
            update_available: boolean;
            stale_after_seconds: number;
            catalog: components["schemas"]["FleetCatalogStatus"];
            current_rollout: components["schemas"]["FleetRollout"] | null;
        };
        FleetOverride: {
            /** @enum {string} */
            action: "hold" | "pin";
            version: string | null;
            updated_at: components["schemas"]["Timestamp"];
        };
        FleetHost: {
            host_id: string;
            host_name: string;
            agent: {
                name: string;
                version: string;
                commit: string;
                os: string;
                arch: string;
                install_method: string;
                update_capable: boolean;
            };
            update: {
                /** @description FleetUpdateState; unknown values are passed through */
                state: string;
                from_version: string;
                to_version: string;
                error: string;
                changed_at: components["schemas"]["NullableTimestamp"];
            };
            first_seen_at: components["schemas"]["Timestamp"];
            last_sync_at: components["schemas"]["Timestamp"];
            rollout_id: string | null;
            override: components["schemas"]["FleetOverride"] | null;
            outdated: boolean;
            supported: boolean;
            /**
             * @description Update decision for the host now
             * @enum {string}
             */
            status: "offer" | "no_catalog" | "mode_off" | "notify_only" | "invalid_version" | "hold" | "not_capable" | "no_rollout" | "rollout_paused" | "rollout_halted" | "rollout_outdated" | "not_in_rollout" | "up_to_date" | "not_in_wave" | "target_unavailable" | "incompatible" | "already_failed" | "no_artifact" | "outside_window";
            status_target: string | null;
        };
    };
    responses: {
        /** @description invalid_argument */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description unauthenticated */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description not_found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description internal */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description timeout */
        Timeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description permission_denied (role, API key read-only, CSRF token, organization) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description already_exists or failed_precondition (last owner) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description resource_exhausted (sign-in rate limit), with Retry-After */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description unavailable (authentication backend), with Retry-After */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        HostID: string;
        /** @description RFC3339 or unix milliseconds. Default now − 1h. */
        From: string;
        /** @description RFC3339 or unix milliseconds. Default now. */
        To: string;
        /** @description Default 100, capped by OPENLOG_API_MAX_ROWS. */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listHosts: {
        parameters: {
            query?: {
                /** @description Default 100, capped by OPENLOG_API_MAX_ROWS. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        hosts: components["schemas"]["Host"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["Internal"];
            504: components["responses"]["Timeout"];
        };
    };
    getHost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                host_id: components["parameters"]["HostID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Host"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
            504: components["responses"]["Timeout"];
        };
    };
    listMetricNames: {
        parameters: {
            query?: {
                host_id?: string;
                /** @description RFC3339 or unix milliseconds. Default now − 1h. */
                from?: components["parameters"]["From"];
                /** @description RFC3339 or unix milliseconds. Default now. */
                to?: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        names: components["schemas"]["MetricMeta"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["Internal"];
            504: components["responses"]["Timeout"];
        };
    };
    getHostMetrics: {
        parameters: {
            query: {
                /** @example system.cpu.utilization */
                name: string;
                /** @description RFC3339 or unix milliseconds. Default now − 1h. */
                from?: components["parameters"]["From"];
                /** @description RFC3339 or unix milliseconds. Default now. */
                to?: components["parameters"]["To"];
                /** @description Go duration, minimum 10s. Default ≈ 300 points, rounded up to 10s (1m on rollup ranges). */
                step?: string;
                /** @description Default `avg` for gauges, `rate` for monotonic sums, `last` for non-monotonic sums. */
                agg?: components["schemas"]["Aggregation"];
                /** @description Comma-separated attribute keys; series are merged by these keys. Default all attributes. */
                group_by?: string;
            };
            header?: never;
            path: {
                host_id: components["parameters"]["HostID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricSeriesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
            504: components["responses"]["Timeout"];
        };
    };
    getHostInventory: {
        parameters: {
            query?: {
                category?: components["schemas"]["InventoryCategory"];
            };
            header?: never;
            path: {
                host_id: components["parameters"]["HostID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
            504: components["responses"]["Timeout"];
        };
    };
    getHostServices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                host_id: components["parameters"]["HostID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
            504: components["responses"]["Timeout"];
        };
    };
    searchInventory: {
        parameters: {
            query: {
                category: components["schemas"]["InventoryCategory"];
                q?: string;
                /** @description Default 100, capped by OPENLOG_API_MAX_ROWS. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["InventorySearchItem"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["Internal"];
            504: components["responses"]["Timeout"];
        };
    };
    listLogs: {
        parameters: {
            query?: {
                host_id?: string;
                service?: string;
                q?: string;
                /** @description Severity number 1-24 or a name (TRACE, DEBUG, INFO, WARN, WARNING, ERROR, FATAL). */
                severity_min?: string;
                trace_id?: string;
                /** @description `file` or `journald` */
                "attr.openlog.log.source"?: string;
                "attr.log.file.path"?: string;
                "attr.log.file.name"?: string;
                /** @description Discovery rule id of the service whose log glob matched the file. */
                "attr.openlog.discovery.id"?: string;
                "attr.openlog.systemd.unit"?: string;
                "attr.openlog.syslog.identifier"?: string;
                /** @description RFC3339 or unix milliseconds. Default now − 1h. */
                from?: components["parameters"]["From"];
                /** @description RFC3339 or unix milliseconds. Default now. */
                to?: components["parameters"]["To"];
                /** @description Default 100, capped by OPENLOG_API_MAX_ROWS. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        logs: components["schemas"]["LogRecord"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            500: components["responses"]["Internal"];
            504: components["responses"]["Timeout"];
        };
    };
    getTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 32 hex characters (case-insensitive). */
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All spans of the trace ordered by start time */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trace"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
            504: components["responses"]["Timeout"];
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getAuthConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfig"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["Unavailable"];
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Signed up and signed in */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getCurrentOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    renameCurrentOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        members: components["schemas"]["Member"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    role: components["schemas"]["Role"];
                };
            };
        };
        responses: {
            /** @description Role changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending invitations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        invitations: components["schemas"]["Invitation"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                    role: components["schemas"]["Role"];
                };
            };
        };
        responses: {
            /** @description Created; the token is shown only in this response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        invitation: components["schemas"]["Invitation"];
                        /** @description oli_… (shown once) */
                        token: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    revokeInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    lookupInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationLookup"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    password: string;
                    name?: string;
                };
            };
        };
        responses: {
            /** @description Joined and signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listLicenseKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingest license keys, including revoked ones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        license_keys: components["schemas"]["LicenseKey"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createLicenseKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NameRequest"];
            };
        };
        responses: {
            /** @description Created; the key is shown only in this response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        license_key: components["schemas"]["LicenseKey"];
                        /** @description olk_… (shown once) */
                        key: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    revokeLicenseKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAPIKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API keys, including revoked ones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        api_keys: components["schemas"]["APIKey"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description RFC3339 or unix milliseconds, in the future */
                    expires_at?: string | null;
                };
            };
        };
        responses: {
            /** @description Created; the key is shown only in this response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        api_key: components["schemas"]["APIKey"];
                        /** @description ola_… (shown once) */
                        key: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    revokeAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked (effective immediately) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's active sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sessions: components["schemas"]["Session"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                /** @description Default 100, max 500. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events: components["schemas"]["AuditEvent"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    getFleetPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The organization's agent update policy (the default policy when none is stored) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetPolicy"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    putFleetPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FleetPolicyInput"];
            };
        };
        responses: {
            /** @description Stored policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetPolicy"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    getFleetSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fleet overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetSummary"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    listFleetHosts: {
        parameters: {
            query?: {
                /** @description Exact reported agent version */
                version?: string;
                /** @description Reported update state */
                state?: components["schemas"]["FleetUpdateState"];
                /** @description Substring of host name or id */
                q?: string;
                /** @description Default 100, max 1000. */
                limit?: number;
                /** @description next_cursor of the previous page */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agents ordered by host name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        hosts: components["schemas"]["FleetHost"][];
                        next_cursor: string | null;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    putFleetHostOverride: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                host_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    action: "hold" | "pin";
                    /** @description Required for pin */
                    version?: string;
                };
            };
        };
        responses: {
            /** @description Override stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetOverride"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteFleetHostOverride: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                host_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    listFleetRollouts: {
        parameters: {
            query?: {
                /** @description Default 20, max 100. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rollouts, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        rollouts: components["schemas"]["FleetRollout"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    pauseFleetRollout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paused rollout */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetRollout"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    resumeFleetRollout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active rollout */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetRollout"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    createFleetRollback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    to_version: string;
                };
            };
        };
        responses: {
            /** @description Rollback rollout created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetRollout"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
}
