using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using OpenTelemetry;
using OpenTelemetry.Context.Propagation;
using OpenTelemetry.Exporter;
using OpenTelemetry.Logs;
using OpenTelemetry.Metrics;
using OpenTelemetry.Resources;
using OpenTelemetry.Trace;

namespace OpenLog.Agent;

/// <summary>
/// The configuration shared by <see cref="OpenLogAgent.Start(OpenLogOptions)"/>, <c>services.AddOpenLog()</c> and the
/// OpenTelemetry .NET automatic instrumentation plugin.
/// </summary>
internal static class OpenLogSetup
{
    /// <summary>ActivitySources of libraries with built-in tracing (no OpenTelemetry instrumentation package needed).</summary>
    internal static readonly (string Instrumentation, string Source)[] NativeSources =
    {
        (Instrumentations.Npgsql, "Npgsql"),
        (Instrumentations.MySqlConnector, "MySqlConnector"),
        (Instrumentations.MassTransit, "MassTransit"),
    };

    internal static readonly (string Instrumentation, string Meter)[] NativeMeters =
    {
        (Instrumentations.Npgsql, "Npgsql"),
        (Instrumentations.MySqlConnector, "MySqlConnector"),
        (Instrumentations.MassTransit, "MassTransit"),
    };

    private static readonly object GlobalsGate = new();
    private static int globalsRefs;
    private static RandomFlagListener? randomFlag;
    private static OpenTelemetryEventForwarder? forwarder;

    /// <summary>
    /// Installs the process-wide pieces: the W3C propagator with the random flag + baggage, the random-flag activity
    /// listener and the forwarding of OpenTelemetry self-diagnostics. Reference counted; dispose to remove.
    /// </summary>
    internal static IDisposable InstallGlobals(OpenLogConfig cfg, Diag diag)
    {
        lock (GlobalsGate)
        {
            if (globalsRefs++ == 0)
            {
                Sdk.SetDefaultTextMapPropagator(new CompositeTextMapPropagator(new TextMapPropagator[] { new OpenLogTraceContextPropagator(), new BaggagePropagator() }));
#if NET
                DistributedContextPropagator.Current = new OpenLogDistributedContextPropagator();
#endif
                randomFlag = new RandomFlagListener();
                if (cfg.LogLevel != DiagnosticLevel.Off) forwarder = new OpenTelemetryEventForwarder(diag);
            }
        }
        return new Release();
    }

    private sealed class Release : IDisposable
    {
        private int disposed;

        public void Dispose()
        {
            if (System.Threading.Interlocked.Exchange(ref disposed, 1) != 0) return;
            lock (GlobalsGate)
            {
                if (--globalsRefs != 0) return;
                randomFlag?.Dispose();
                randomFlag = null;
                forwarder?.Dispose();
                forwarder = null;
                Sdk.SetDefaultTextMapPropagator(new CompositeTextMapPropagator(new TextMapPropagator[] { new TraceContextPropagator(), new BaggagePropagator() }));
#if NET
                DistributedContextPropagator.Current = DistributedContextPropagator.CreateDefaultPropagator();
#endif
            }
        }
    }

    internal static void ConfigureResource(ResourceBuilder rb, OpenLogConfig cfg, Diag? diag)
    {
        var detector = new OpenLogResourceDetector(cfg);
        rb.Clear().AddTelemetrySdk().AddDetector(detector);
        if (diag != null)
        {
            // Build once to log the host.id source (detection is cheap and cached by the providers afterwards).
            _ = detector.Attributes();
            if (detector.HostIdSource == "generated")
            {
                diag.Info("host.id generated by the .NET agent; it links to an infra agent only if both read the same machine-id (see README: host linking)");
            }
            diag.Debug("resource", ("host.id.source", detector.HostIdSource));
        }
    }

    internal static OtlpExporterOptions ExporterOptions(OpenLogConfig cfg, string signal)
    {
        var grpc = cfg.Protocol == OpenLogConfig.ProtocolGrpc;
#pragma warning disable CS0618 // OTLP/gRPC on netstandard2.0/.NET Framework needs an HttpClientFactory (documented; http/protobuf is the default)
        var protocol = grpc ? OtlpExportProtocol.Grpc : OtlpExportProtocol.HttpProtobuf;
#pragma warning restore CS0618
        return new OtlpExporterOptions
        {
            Protocol = protocol,
            Endpoint = new Uri(grpc ? cfg.Endpoint : cfg.Endpoint + "/v1/" + signal),
            Headers = string.Join(",", cfg.Headers.Select(kv => kv.Key + "=" + kv.Value)),
            Compression = (OtlpExportCompression)Enum.Parse(typeof(OtlpExportCompression), cfg.Gzip ? "gzip" : "none", ignoreCase: true),
            TimeoutMilliseconds = (int)Math.Min(int.MaxValue, cfg.ExportTimeout.TotalMilliseconds),
            UserAgentProductIdentifier = "openlog-dotnet/" + AgentVersion.Version,
        };
    }

    // RecordException does not exist on every target-framework build of the instrumentations: the net462 build of
    // OpenTelemetry.Instrumentation.SqlClient that .NET Framework apps load has no such property, so setting it directly
    // from this netstandard2.0 assembly fails with MissingMethodException. Set it only where it exists.
    private static void TryRecordException(object options) =>
        options.GetType().GetProperty("RecordException")?.SetValue(options, true);

    /// <summary>Sampler, sources, instrumentations, openlog processors and (optionally) the OTLP exporter.</summary>
    internal static void ConfigureTracing(TracerProviderBuilder b, OpenLogConfig cfg, Diag diag, bool addExporter)
    {
        b.SetSampler(OpenLogSampler.Create(cfg.SamplingRatio, cfg.SamplingRV));
#if NET
        if (cfg.IsEnabled(Instrumentations.AspNetCore) || cfg.IsEnabled(Instrumentations.Grpc))
        {
            var ignore = new HashSet<string>(cfg.HttpIgnorePaths, StringComparer.Ordinal);
            b.AddAspNetCoreInstrumentation(o =>
            {
                o.RecordException = true;
                if (ignore.Count > 0) o.Filter = ctx => !ignore.Contains(ctx.Request.Path.Value ?? "");
                if (!cfg.IsEnabled(Instrumentations.AspNetCore))
                {
                    o.Filter = ctx => ctx.Request.ContentType?.StartsWith("application/grpc", StringComparison.Ordinal) == true;
                }
            });
        }
#endif
        if (cfg.IsEnabled(Instrumentations.HttpClient))
        {
            b.AddHttpClientInstrumentation(o => TryRecordException(o));
        }
        if (cfg.IsEnabled(Instrumentations.SqlClient))
        {
            b.AddSqlClientInstrumentation(o => TryRecordException(o));
        }
        foreach (var (name, source) in NativeSources)
        {
            if (cfg.IsEnabled(name)) b.AddSource(source);
        }
        if (cfg.IsEnabled(Instrumentations.Redis)) TryAddRedis(b, diag);
        foreach (var s in cfg.ActivitySources) b.AddSource(s);
        b.AddProcessor(new RouteProcessor());
        b.AddProcessor(new DbStatementProcessor(cfg.DbQueryText));
        cfg.ConfigureTracing?.Invoke(b);
        if (addExporter)
        {
            b.AddProcessor(new BatchActivityExportProcessor(
                new OtlpTraceExporter(ExporterOptions(cfg, "traces")),
                maxQueueSize: 4096,
                scheduledDelayMilliseconds: 5000,
                exporterTimeoutMilliseconds: (int)Math.Max(30_000, cfg.ExportTimeout.TotalMilliseconds),
                maxExportBatchSize: 512));
        }
    }

    /// <summary>
    /// Enables OpenTelemetry.Instrumentation.StackExchangeRedis when the application references it (the package is
    /// prerelease and brings StackExchange.Redis, so the agent does not depend on it).
    /// </summary>
    private static void TryAddRedis(TracerProviderBuilder b, Diag diag)
    {
        try
        {
            var t = Type.GetType("OpenTelemetry.Trace.TracerProviderBuilderExtensions, OpenTelemetry.Instrumentation.StackExchangeRedis", throwOnError: false);
            var m = t?.GetMethods(BindingFlags.Public | BindingFlags.Static)
                .FirstOrDefault(x => x.Name == "AddRedisInstrumentation" && x.GetParameters().Length == 1 && x.GetParameters()[0].ParameterType == typeof(TracerProviderBuilder));
            if (m == null) return;
            m.Invoke(null, new object[] { b });
            diag.Debug("StackExchange.Redis instrumentation enabled");
        }
        catch (Exception e)
        {
            diag.Warn("StackExchange.Redis instrumentation not enabled", ("error", e.InnerException?.Message ?? e.Message));
        }
    }

    internal static void ConfigureMetrics(MeterProviderBuilder b, OpenLogConfig cfg, bool addExporter)
    {
#if NET
        if (cfg.IsEnabled(Instrumentations.AspNetCore)) b.AddAspNetCoreInstrumentation();
#endif
        if (cfg.IsEnabled(Instrumentations.HttpClient)) b.AddHttpClientInstrumentation();
        if (cfg.RuntimeMetrics)
        {
            b.AddRuntimeInstrumentation();
            ProcessMetrics.EnsureCreated();
            b.AddMeter(ProcessMetrics.MeterName);
        }
        foreach (var (name, meter) in NativeMeters)
        {
            if (cfg.IsEnabled(name)) b.AddMeter(meter);
        }
        foreach (var m in cfg.Meters) b.AddMeter(m);
        cfg.ConfigureMetrics?.Invoke(b);
        if (addExporter)
        {
            var interval = (int)Math.Max(1, Math.Min(int.MaxValue, cfg.MetricExportInterval.TotalMilliseconds));
            b.AddReader(new PeriodicExportingMetricReader(
                new OtlpMetricExporter(ExporterOptions(cfg, "metrics")),
                exportIntervalMilliseconds: interval,
                exportTimeoutMilliseconds: Math.Min(Math.Max((int)cfg.ExportTimeout.TotalMilliseconds, 1), interval)));
        }
    }

    internal static void ConfigureLogging(LoggerProviderBuilder b, OpenLogConfig cfg, bool addExporter)
    {
        cfg.ConfigureLogging?.Invoke(b);
        if (addExporter && cfg.LogsExport)
        {
            b.AddProcessor(new BatchLogRecordExportProcessor(
                new OtlpLogExporter(ExporterOptions(cfg, "logs")),
                maxQueueSize: 4096,
                scheduledDelayMilliseconds: 2000,
                exporterTimeoutMilliseconds: (int)Math.Max(30_000, cfg.ExportTimeout.TotalMilliseconds),
                maxExportBatchSize: 512));
        }
    }

    internal static void ConfigureLoggerOptions(OpenTelemetryLoggerOptions o)
    {
        o.IncludeFormattedMessage = true;
        o.IncludeScopes = true;
        o.ParseStateValues = true;
    }

    internal static void LogStarted(OpenLogConfig cfg, Diag diag, string mode)
    {
        diag.Info("started",
            ("mode", mode),
            ("service.name", cfg.ServiceName),
            ("endpoint", cfg.Endpoint),
            ("protocol", cfg.Protocol),
            ("sampling_ratio", cfg.SamplingRatio),
            ("version", AgentVersion.Version));
    }
}

#if NET
/// <summary>
/// Runtime-level propagator (HttpClient's DiagnosticsHandler, ASP.NET Core hosting): W3C tracecontext keeping the
/// random flag, plus baggage. The OpenTelemetry instrumentations also inject/extract with the SDK propagator.
/// </summary>
internal sealed class OpenLogDistributedContextPropagator : DistributedContextPropagator
{
    private static readonly DistributedContextPropagator Inner = CreateDefaultPropagator();

    public override IReadOnlyCollection<string> Fields => Inner.Fields;

    public override void Inject(Activity? activity, object? carrier, PropagatorSetterCallback? setter)
    {
        if (activity == null || setter == null || activity.IdFormat != ActivityIdFormat.W3C)
        {
            Inner.Inject(activity, carrier, setter);
            return;
        }
        var flags = (int)activity.ActivityTraceFlags & 0x03;
        setter(carrier, OpenLogTraceContextPropagator.TraceParent,
            "00-" + activity.TraceId.ToHexString() + "-" + activity.SpanId.ToHexString() + "-" + flags.ToString("x2", System.Globalization.CultureInfo.InvariantCulture));
        if (!string.IsNullOrEmpty(activity.TraceStateString)) setter(carrier, OpenLogTraceContextPropagator.TraceState, activity.TraceStateString);
        // baggage
        var baggage = activity.Baggage.ToList();
        if (baggage.Count > 0)
        {
            setter(carrier, "baggage", string.Join(",", baggage.Select(kv => Uri.EscapeDataString(kv.Key) + "=" + Uri.EscapeDataString(kv.Value ?? ""))));
        }
    }

    public override void ExtractTraceIdAndState(object? carrier, PropagatorGetterCallback? getter, out string? traceId, out string? traceState)
    {
        Inner.ExtractTraceIdAndState(carrier, getter, out traceId, out traceState);
    }

    public override IEnumerable<KeyValuePair<string, string?>>? ExtractBaggage(object? carrier, PropagatorGetterCallback? getter)
    {
        return Inner.ExtractBaggage(carrier, getter);
    }
}
#endif
