{{- if and .Values.licenseKey (not .Values.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openlog-agent.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openlog-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.existingSecret.key }}: {{ .Values.licenseKey | quote }}
{{- end }}
