package openlog

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"sync"
	"time"

	"github.com/go-logr/logr"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/log/global"
	"go.opentelemetry.io/otel/propagation"
	sdklog "go.opentelemetry.io/otel/sdk/log"
	sdkmetric "go.opentelemetry.io/otel/sdk/metric"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
)

// ShutdownFunc flushes buffered telemetry and stops the exporters. If ctx has no
// deadline, the configured shutdown timeout (default 5s) applies.
type ShutdownFunc func(context.Context) error

var (
	startMu sync.Mutex
	running bool
)

// ErrAlreadyStarted is returned when Start is called while a previous Start is active.
var ErrAlreadyStarted = errors.New("openlog: already started; call the previous shutdown first")

// Start configures OpenTelemetry for openlog and installs the global TracerProvider,
// MeterProvider, LoggerProvider and W3C tracecontext + baggage propagators.
//
// Configuration precedence: options > OPENLOG_* > OTEL_* > defaults. Export problems are
// logged (rate limited) and never returned from instrumented code paths; Start itself
// only fails on invalid configuration.
//
//	shutdown, err := openlog.Start(ctx, openlog.WithServiceName("checkout"))
//	if err != nil { log.Fatal(err) }
//	defer shutdown(context.Background())
func Start(ctx context.Context, opts ...Option) (ShutdownFunc, error) {
	return start(ctx, os.LookupEnv, os.Stderr, opts)
}

func start(ctx context.Context, lookup lookupFunc, diagOut io.Writer, opts []Option) (ShutdownFunc, error) {
	cfg, warnings, err := loadConfig(lookup, opts)
	if err != nil {
		return noopShutdown, err
	}
	log := diagLogger(diagOut, cfg.LogLevel)
	for _, w := range warnings {
		log.Warn(w)
	}
	if !cfg.Enabled {
		log.Info("disabled (OPENLOG_ENABLED=false)")
		return noopShutdown, nil
	}

	startMu.Lock()
	defer startMu.Unlock()
	if running {
		return noopShutdown, ErrAlreadyStarted
	}

	res, hostIDSource, err := buildResource(ctx, cfg, lookup)
	if err != nil {
		// Partial resources (e.g. a failed detector) are still usable.
		log.Debug("resource detection", "error", err)
	}
	if hostIDSource == hostIDSourceGenerated {
		log.Info("host.id generated by the Go agent; it links to an infra agent only if both read the same machine-id (see README: host linking)")
	}
	exp, err := newExporters(ctx, cfg)
	if err != nil {
		return noopShutdown, fmt.Errorf("openlog: exporters: %w", err)
	}

	tp := sdktrace.NewTracerProvider(
		sdktrace.WithResource(res),
		sdktrace.WithSampler(newSampler(cfg.SamplingRatio, cfg.SamplingRV)),
		sdktrace.WithBatcher(exp.trace,
			sdktrace.WithMaxQueueSize(4096),
			sdktrace.WithMaxExportBatchSize(512),
			sdktrace.WithBatchTimeout(5*time.Second),
			sdktrace.WithExportTimeout(cfg.ExportTimeout+cfg.retry.elapsed),
		),
	)
	readerOpts := []sdkmetric.PeriodicReaderOption{sdkmetric.WithInterval(cfg.MetricInterval), sdkmetric.WithTimeout(cfg.ExportTimeout + cfg.retry.elapsed)}
	if cfg.RuntimeMetrics {
		readerOpts = append(readerOpts, sdkmetric.WithProducer(newRuntimeProducer()))
	}
	mp := sdkmetric.NewMeterProvider(
		sdkmetric.WithResource(res),
		sdkmetric.WithReader(sdkmetric.NewPeriodicReader(exp.metric, readerOpts...)),
	)
	lp := sdklog.NewLoggerProvider(
		sdklog.WithResource(res),
		sdklog.WithProcessor(sdklog.NewBatchProcessor(exp.log,
			sdklog.WithMaxQueueSize(4096),
			sdklog.WithExportMaxBatchSize(512),
			sdklog.WithExportInterval(2*time.Second),
			sdklog.WithExportTimeout(cfg.ExportTimeout+cfg.retry.elapsed),
		)),
	)

	otel.SetLogger(logr.FromSlogHandler(log.Handler()))
	otel.SetErrorHandler(newErrorHandler(log))
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}, propagation.Baggage{}))
	otel.SetTracerProvider(randomTracerProvider{tp: tp})
	otel.SetMeterProvider(mp)
	global.SetLoggerProvider(lp)
	running = true

	log.Info("started", "service.name", cfg.ServiceName, "endpoint", cfg.Endpoint, "protocol", cfg.Protocol,
		"sampling_ratio", cfg.SamplingRatio, "host.id.source", hostIDSource, "version", Version)

	var once sync.Once
	var shutdownErr error
	return func(ctx context.Context) error {
		once.Do(func() {
			if _, ok := ctx.Deadline(); !ok {
				var cancel context.CancelFunc
				ctx, cancel = context.WithTimeout(ctx, cfg.ShutdownTimeout)
				defer cancel()
			}
			var wg sync.WaitGroup
			errs := make([]error, 3)
			for i, f := range []func(context.Context) error{tp.Shutdown, mp.Shutdown, lp.Shutdown} {
				wg.Go(func() { errs[i] = f(ctx) })
			}
			wg.Wait()
			shutdownErr = errors.Join(errs...)
			if shutdownErr != nil {
				log.Warn("shutdown", "error", shutdownErr)
			}
			startMu.Lock()
			running = false
			startMu.Unlock()
		})
		return shutdownErr
	}, nil
}

func noopShutdown(context.Context) error { return nil }
